"""Initial migration.

Revision ID: 10f94d82a08
Revises: None
Create Date: 2017-07-15 00:03:03.002636

"""

# revision identifiers, used by Alembic.
revision = '10f94d82a08'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
